website/__init__.py
from flask import Flask

def create_app():

    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'secretkey'

    from .views import views
    app.register_blueprint(views, url_prefix='/')

    return app

website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
import pandas as pd


# -- MODELOS --
from models.models import Pessoa, Busca


# -- INÍCIO DO APP --
views = Blueprint('views', __name__)


# -- PÁGINA INICIAL --
@views.route('/')
def home():
    

    """
    Rota inicial.
    Não é necessário modificar nada nessa função
    """


    return render_template('home.html')


# -- CADASTRO --
@views.route('/cadastro')
def cadastro():
    return render_template('cadastro.html')


@views.route('/novo_cliente', methods=['POST', ])
def novo_cliente():


    """
    Função para cadastro de novos clientes. Deverá pegar as informações do forms e salvar numa nova linha no csv.
    Necessário também salvar as informações de endereço provindas da API de CEP
    """
    

    info_nome = request.form['nome']
    info_sobrenome = request.form['sobrenome']
    info_email = request.form['email']
    info_cep = request.form['cep']


    pessoa1 = Pessoa(info_nome, info_sobrenome, info_email, info_cep)


    pessoa = {
        'nome': pessoa1.nome,
        'sobrenome': pessoa1.sobrenome,
        'email': pessoa1.email,
    }
    # coleta as informações cadastradas
    df1 = pd.DataFrame(data=pessoa, index=[0])

    
    print('cheguei na api')
    df2 = pessoa1.api()
    print('passei da api')
    try:
        # coleta informações da API
        # une as informações
        result = pd.concat([df1, df2], axis=1, ignore_index=True)
        result.columns = Pessoa.columns_name  # renomeia as informações

        df_final = pd.concat([Pessoa.df_principal, result]
                             )  # constrói o dataset final

        Pessoa.df_principal = df_final

        flash('Cliente cadastrado com sucesso')
        print('deu certo em views')
        return redirect(url_for('views.clientes'))

    except:
        print('deu errado em views')
        flash('Cep Não Encontrado ou Inválido')
        return redirect(url_for('views.cadastro'))


# -- CONSULTA CEP --
@views.route('/consulta-cep')
def consulta_cep():
    return render_template('consulta_cep.html', dic=Busca.dicionario)


@views.route('/validando_busca', methods=['POST', ])
def consulta():
    busca_cep = request.form['cep_busca']
    result = Busca(busca_cep)
    busca_final = Busca.pesquisa(result)
    Busca.dicionario = busca_final
    return redirect(url_for('views.consulta_cep'))


# -- CLIENTES CADASTRADOS --
@views.route('/clientes')
def clientes():
    """
    Rota para aba de clientes. Mostra na tela uma representação do csv de clientes
    Não é necessário modificar nada nessa função
    """
    Pessoa.df_principal.to_csv('data/clientes.csv', index=False,
                               sep=';')  # executa a função e salva os dados no csv
    return render_template('/clientes.html',
                           df=Pessoa.df_principal,
                           titles=Pessoa.df_principal.columns.values)

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />

    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round|Open+Sans"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
    />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />

    <title>{% block title %}Website{% endblock %}</title>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a href="/" class="navbar-brand">Website</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          <a href="/clientes" class="nav-item nav-link" id="accounts">Clientes</a>
          <a href="/cadastro" class="nav-item nav-link" id="users">Cadastro</a>
          <a href="/consulta-cep" class="nav-item nav-link" id="users">Consulta CEP</a>
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} 
    
    {% if messages %} 
    
    {% for category, message in messages %}

    <div class="container" id="flash">
      {% if category=='error' %}
      <div class="alert alert-danger alter-dismissable fade show" role="alert">
        {{message}}
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% else %}
      <div class="alert alert-success alter-dismissable fade show" role="alert">
        {{message}}
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endif %}
    </div>

    {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <script
      type="text/javascript"
      src="{{url_for('static', filename='index.js')}}"
    ></script>
  </body>
</html>

website/templates/cadastro.html
{% extends "base.html" %}
{% block title %}Website{% endblock %}

{% block content %}
<br>
<h1 align="center">Cadastrar novo cliente</h1>

<form action="{{ url_for('views.novo_cliente') }}" method="POST">
    <div class="row">
        <div class="col-6">
            <div class="form-group">
                <label for="nome">Nome</label>
                <input type="text" required class="form-control" id="nome" name="nome" placeholder="Nome">
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                <label for="sobrenome">Sobrenome</label>
                <input type="text" required class="form-control" id="sobrenome" name="sobrenome" placeholder="Sobrenome">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" required class="form-control" id="email" name="email" placeholder="email@email.com">
            </div>
        </div> 
    </div>
    <div class="row">
        <div class="col-12">
            <div class="form-group">
                <label for="cep">CEP</label>
                <input type="number" required minlength="8" maxlength="8" class="form-control" id="cep" name="cep" placeholder="CEP">
            </div>
        </div> 
    </div>
    <br />
    
    <button type="submit" class="btn btn-primary">Concluir</button>
</form>


{% endblock %}

website/templates/clientes.html
{% extends "base.html" %}
{% block title %}Website - Clientes Cadastrados{% endblock %}

{% block content %}
<br>
<h1 align="center">Clientes Cadastrados</h1>
<br>

<table class="table align-middle">
    <thead>
        <tr>
            {%for title in titles %}
            <th>{{title.title()}}</th>
            {% endfor %}
        </tr>
    </thead>

    <tbody>
        {% for index, row in df.iterrows() %}
        <tr>
            {%for title in titles %}
            <td>{{row[title]}}</td>
            {% endfor %}
        </tr>
        {% endfor %}
        
    </tbody>
</table>


{% endblock %}

website/templates/consulta_cep.html
{% extends "base.html" %}
{% block title %}Website{% endblock %}

{% block content %}
<br>
<h1 align="center">Consulta CEP</h1>

<form action="{{ url_for('views.consulta') }}" method="POST">
    <div class="container">
        <div class="form-group">
            <div class="row">
                <div class="col-6">
                    <label for="cep">CEP:</label>
                    <input type="text" minlength="8" maxlength="8" id="cep" name="cep_busca" class="form-control"
                        required>
                    <style>
                        input[type=number]::-webkit-inner-spin-button,
                        input[type=number]::-webkit-outer-spin-button {
                            -webkit-appearance: none;
                            margin: 0;
                        }
                    </style>
                </div>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Consultar</button>
    </div>
</form>

<br>



<div class="container">
    <div class="row">
        <div class="col-4">
            <label for="cep">CEP:</label>
        </div>
        <div class="col-8">
            <label for="cep_result">{{ dic['cep'] }}</label>
        </div>
    </div>

    <div class="row">
        <div class="col-4">
            <label for="logradouro">Logradouro:</label>
        </div>
        <div class="col-8">
            <label for="logradouro_result">{{ dic['logradouro'] }}</label>
        </div>
    </div>

    <div class="row">
        <div class="col-4">
            <label for="complemento">Complemento:</label>
        </div>
        <div class="col-8">
            <label for="complemento_result">{{ dic['complemento'] }}</label>
        </div>
    </div>

    <div class="row">
        <div class="col-4">
            <label for="bairro">Bairro:</label>
        </div>
        <div class="col-8">
            <label for="bairro_result">{{ dic['bairro'] }}</label>
        </div>
    </div>

    <div class="row">
        <div class="col-4">
            <label for="localidade">Localidade:</label>
        </div>
        <div class="col-8">
            <label for="localidade_result">{{ dic['localidade'] }}</label>
        </div>
    </div>

    <div class="row">
        <div class="col-4">
            <label for="uf">UF:</label>
        </div>
        <div class="col-8">
            <label for="uf_result">{{ dic['uf'] }}</label>
        </div>
    </div>

    <div class="row">
        <div class="col-4">
            <label for="ibge">IBGE:</label>
        </div>
        <div class="col-8">
            <label for="ibge_result">{{ dic['ibge'] }}</label>
        </div>
    </div>

    <div class="row">
        <div class="col-4">
            <label for="gia">GIA:</label>
        </div>
        <div class="col-8">
            <label for="gia_result">{{ dic['gia'] }}</label>
        </div>
    </div>

    <div class="row">
        <div class="col-4">
            <label for="ddd">DDD:</label>
        </div>
        <div class="col-8">
            <label for="ddd_result">{{ dic['ddd'] }}</label>
        </div>
    </div>

    <div class="row">
        <div class="col-4">
            <label for="siafi">Siafi:</label>
        </div>
        <div class="col-8">
            <label for="siafi_result">{{ dic['siafi'] }}</label>
        </div>
    </div>

</div>

{% endblock %}

website/templates/home.html
{% extends "base.html" %}
{% block title %}Website{% endblock %}

{% block content %}
<br>
<h1 align="center">Bem Vindo</h1>

<h4 align="center">Faça um cadastro e busque endereços</h4>

<h1 style="margin-top: 5rem;" align="center">
    <img src="../static/video/projeto1-cadastro-clientes-flask.gif" width="600" height="300">
</h1>

{% endblock %}